## Optional Assignment: Advanced NumPy and PyTorch Operations with MNIST
*  PyTorch, a popular open-source machine learning library for Python.
* The MNIST (Modified National Institute of Standards and Technology) dataset is a widely-used dataset in the field of machine learning and computer vision. 

# Intro about PyTorch
PyTorch is an open-source machine learning library for Python that is primarily used for building and training deep neural networks. It was developed by the AI research group at Facebook's AI Research lab (FAIR) and is now widely used in the machine learning and deep learning community.

PyTorch is a powerful and flexible deep learning framework that has gained significant popularity in the machine learning community. Its dynamic computational graphs, ease of use, and strong support for research and production make it a compelling choice for a wide range of machine learning applications.

In [2]:
# NumPy and PyTorch Tensor Operations Assignment

import numpy as np
import torch
import matplotlib.pyplot as plt
from torchvision import datasets, transforms

# Create a random NumPy array
np_random = np.random.rand(3, 4)
print("Random NumPy array:")
print(np_random)

# Create a random PyTorch tensor
torch_random = torch.rand(3, 4)
print("\nRandom PyTorch tensor:")
print(torch_random)



Random NumPy array:
[[0.68555846 0.15298211 0.31720029 0.67183991]
 [0.26901234 0.34192065 0.81783708 0.93006806]
 [0.77366008 0.14163495 0.87927009 0.58508256]]

Random PyTorch tensor:
tensor([[0.3122, 0.4392, 0.7233, 0.4178],
        [0.3429, 0.3051, 0.7882, 0.3394],
        [0.3214, 0.1076, 0.6643, 0.1478]])


In [3]:
#  Reshaping
# Reshape NumPy array
np_reshaped = np_random.reshape(2, 6)
print("Reshaped NumPy array:")
print(np_reshaped)

# Reshape PyTorch tensor
torch_reshaped = torch_random.reshape(2, 6)
print("\nReshaped PyTorch tensor:")
print(torch_reshaped)

Reshaped NumPy array:
[[0.68555846 0.15298211 0.31720029 0.67183991 0.26901234 0.34192065]
 [0.81783708 0.93006806 0.77366008 0.14163495 0.87927009 0.58508256]]

Reshaped PyTorch tensor:
tensor([[0.3122, 0.4392, 0.7233, 0.4178, 0.3429, 0.3051],
        [0.7882, 0.3394, 0.3214, 0.1076, 0.6643, 0.1478]])


In [4]:
# NumPy array multiplication
np_mult = np.multiply(np_random, 2)
print("NumPy array multiplication:")
print(np_mult)

# PyTorch tensor multiplication
torch_mult = torch.mul(torch_random, 2)
print("\nPyTorch tensor multiplication:")
print(torch_mult)

NumPy array multiplication:
[[1.37111693 0.30596422 0.63440057 1.34367981]
 [0.53802468 0.6838413  1.63567417 1.86013613]
 [1.54732016 0.28326991 1.75854017 1.17016512]]

PyTorch tensor multiplication:
tensor([[0.6244, 0.8784, 1.4467, 0.8355],
        [0.6858, 0.6102, 1.5763, 0.6788],
        [0.6428, 0.2153, 1.3285, 0.2957]])


In [5]:
#  Permute shape
# Permute NumPy array
np_permuted = np.transpose(np_random, (1, 0))
print("Permuted NumPy array:")
print(np_permuted)

# Permute PyTorch tensor
torch_permuted = torch_random.permute(1, 0)
print("\nPermuted PyTorch tensor:")
print(torch_permuted)


Permuted NumPy array:
[[0.68555846 0.26901234 0.77366008]
 [0.15298211 0.34192065 0.14163495]
 [0.31720029 0.81783708 0.87927009]
 [0.67183991 0.93006806 0.58508256]]

Permuted PyTorch tensor:
tensor([[0.3122, 0.3429, 0.3214],
        [0.4392, 0.3051, 0.1076],
        [0.7233, 0.7882, 0.6643],
        [0.4178, 0.3394, 0.1478]])


In [6]:
# Convert between NumPy and PyTorch
# NumPy to PyTorch
np_to_torch = torch.from_numpy(np_random)
print("NumPy to PyTorch:")
print(np_to_torch)

# PyTorch to NumPy
torch_to_np = torch_random.numpy()
print("\nPyTorch to NumPy:")
print(torch_to_np)

NumPy to PyTorch:
tensor([[0.6856, 0.1530, 0.3172, 0.6718],
        [0.2690, 0.3419, 0.8178, 0.9301],
        [0.7737, 0.1416, 0.8793, 0.5851]], dtype=torch.float64)

PyTorch to NumPy:
[[0.3121832  0.43921524 0.72333115 0.4177606 ]
 [0.34288007 0.3050769  0.7881573  0.33939385]
 [0.32141495 0.10764658 0.66427356 0.14784086]]


In [7]:
# NumPy and PyTorch Tensor Operations on MNIST Dataset

import numpy as np
import torch
import matplotlib.pyplot as plt
from torchvision import datasets, transforms

# Load MNIST dataset
transform = transforms.Compose([transforms.ToTensor()])
mnist_train = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
mnist_test = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# Create a batch of MNIST images
batch_size = 64
train_loader = torch.utils.data.DataLoader(mnist_train, batch_size=batch_size, shuffle=True)
images, labels = next(iter(train_loader))
print("Shape of the batch:", images.shape)

# Concatenation
# Concatenate along the batch dimension
concat_images = torch.cat((images, images), dim=0)

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9912422/9912422 [02:31<00:00, 65268.79it/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 168905.80it/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1648877/1648877 [00:16<00:00, 100852.15it/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4542/4542 [00:00<00:00, 1150116.44it/s]

Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw

Shape of the batch: torch.Size([64, 1, 28, 28])


In [8]:

# Cell 4: Add and remove dimensions
# TODO: Add a new dimension to the 'images' tensor
expanded_images = None  # Your code here
print("Shape after adding dimension:", expanded_images.shape)

# TODO: Remove the added dimension from 'expanded_images'
squeezed_images = None  # Your code here
print("Shape after removing dimension:", squeezed_images.shape)

# Cell 5: Flatten tensors
# TODO: Flatten the 'images' tensor to have shape (batch_size, -1)
flattened_images = None  # Your code here
print("Shape of flattened images:", flattened_images.shape)

# Cell 6: Slicing
# TODO: Get the first 10 images from the 'images' tensor
first_10_images = None  # Your code here
print("Shape of first 10 images:", first_10_images.shape)

# TODO: Get all channels of the first image
first_image_all_channels = None  # Your code here
print("Shape of first image (all channels):", first_image_all_channels.shape)

# TODO: Get a 14x14 slice from the center of each image
center_slice = None  # Your code here
print("Shape of center slice:", center_slice.shape)

# Cell 7: Visualize original and manipulated images
# TODO: Complete the visualization code
plt.figure(figsize=(15, 5))

# Original image
plt.subplot(1, 3, 1)
plt.imshow(images[0].squeeze(), cmap='gray')
plt.title("Original Image")
plt.axis('off')

# Flattened and reshaped image
plt.subplot(1, 3, 2)
# TODO: Display the first flattened image, reshaping it back to 28x28
# Your code here

# Center slice
plt.subplot(1, 3, 3)
# TODO: Display the center slice of the first image
# Your code here

plt.tight_layout()
plt.show()

# Cell 8: Convert between NumPy and PyTorch
# TODO: Convert the PyTorch 'images' tensor to a NumPy array
np_images = None  # Your code here
print("Shape of NumPy array:", np_images.shape)

# TODO: Convert the NumPy array back to a PyTorch tensor
torch_images = None  # Your code here
print("Shape of PyTorch tensor:", torch_images.shape)



AttributeError: 'NoneType' object has no attribute 'shape'